apiVersion: autoscaling.eventscale.com/v1
kind: EventScalePolicy
metadata:
  labels:
    app.kubernetes.io/name: predictive-scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventscalepolicy-sample
spec:
  # TODO(user): Add fields here
