apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
  namespace: ticketing
  labels:
    app: ticket-api
    autoscaling.eventscale.com/managed: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
        - name: ticket-api
          image: jaewon0077/ticketing-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: localdb
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: ticketing
            - name: DB_USER
              value: ticketing
            - name: DB_PASSWORD
              value: ticketing1234
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
